connect sys as sysdba
CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/ORCLCDB/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

alter session set container=orclpdb1;

CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

alter session set container=cdb$root;

CREATE USER c##dbzlmuser IDENTIFIED BY comPlex_456 DEFAULT TABLESPACE logminer_tbs QUOTA UNLIMITED ON logminer_tbs CONTAINER=ALL;

GRANT CREATE SESSION TO c##dbzlmuser CONTAINER=ALL;
GRANT SET CONTAINER TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE to c##dbzlmuser CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##dbzlmuser CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbzlmuser CONTAINER=ALL;
GRANT LOGMINING TO c##dbzlmuser CONTAINER=ALL;

GRANT CREATE TABLE TO c##dbzlmuser CONTAINER=ALL;
GRANT LOCK ANY TABLE TO c##dbzlmuser CONTAINER=ALL;
GRANT CREATE SEQUENCE TO c##dbzlmuser CONTAINER=ALL;

GRANT EXECUTE ON DBMS_LOGMNR TO c##dbzlmuser CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbzlmuser CONTAINER=ALL;

GRANT SELECT ON V_$LOG TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO c##dbzlmuser CONTAINER=ALL;

GRANT SELECT ON V_$MYSTAT TO c##dbzlmuser CONTAINER=ALL;
GRANT SELECT ON V_$STATNAME TO c##dbzlmuser CONTAINER=ALL;
